openapi: 3.0.0
x-stoplight:
  id: zvpj576gvy7j9
info:
  title: Backend API Final Project 4
  version: '1.0'
  description: The API documentation here contains all the api documentation to support the Binar Academy Final Project Backend Developer
  contact:
    name: Syifaul Qolbi
    email: syifaulqolbi32@gmail.com
servers:
  - url: 'https://antariksa-api.up.railway.app'
    description: Production Environtment
  - url: 'https://backend-4.up.railway.app/'
    description: Staging Environtment
paths:
  /auth/register:
    post:
      summary: Create Buyer Register Endpoint
      operationId: post-auth-register
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      role:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    message: Succes
                    data:
                      email: petotudin123@mail.com
                      name: Udin Petot
                      role: Buyer
              examples:
                Example 1:
                  value:
                    status: true
                    message: Succes
                    data:
                      email: petotudin123@mail.com
                      name: Udin Petot
                      role: Buyer
        '400':
          description: email not match
        '403':
          description: email already used
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                gender:
                  type: string
                phone:
                  type: string
              x-examples:
                Example 1:
                  name: Udin Petot
                  email: petotudin123@mail.com
                  password: Petot123#
                  gender: Female
                  phone: '123456789012'
            examples:
              Example 1:
                value:
                  name: Udin Petot
                  email: petotudin123@mail.com
                  password: Petot123#
                  gender: Female
                  phone: '123456789012'
        description: In this body you can create new buyer
      description: ''
      tags:
        - Auth Endpoint
  /auth/login:
    post:
      summary: Login Buyer Endpoint
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                      role:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    data:
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IlN5aWZhIiwiZW1haWwiOiJzeWlmYXVscW9sYmkzNUBnbWFpbC5jb20iLCJyb2xlIjoiQnV5ZXIiLCJpYXQiOjE2Njk4Mzk2ODR9.Rg3zv3MGeGRwSYAvEoo76j6MLM0g_i9BWEnMyeXNU3U
                      role: Buyer
              examples:
                Example 1:
                  value:
                    status: true
                    data:
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IlN5aWZhIiwiZW1haWwiOiJzeWlmYXVscW9sYmkzNUBnbWFpbC5jb20iLCJyb2xlIjoiQnV5ZXIiLCJpYXQiOjE2Njk4Mzk2ODR9.Rg3zv3MGeGRwSYAvEoo76j6MLM0g_i9BWEnMyeXNU3U
                      role: Buyer
        '400':
          description: Email not found
        '401':
          description: Password doesn't match
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              x-examples:
                Example 1:
                  email: syifaulqolbi35@gmail.com
                  password: '123'
            examples:
              Example 1:
                value:
                  email: syifaulqolbi35@gmail.com
                  password: '123'
        description: In this endpoint you can login to your application
      tags:
        - Auth Endpoint
  /auth/forgot-password:
    post:
      summary: Forgot Password Endpoint
      operationId: post-auth-forgot-password
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              x-examples:
                Example 1:
                  email: syifaulqolbi32@gmail.com
            examples:
              Example 1:
                value:
                  email: syifasyifa123@gmail.com
        description: 'Masukkan email user yang ingin diubah password nya :)'
      tags:
        - Auth Endpoint
  /auth/reset-password:
    post:
      summary: Reset Password Endpoint
      operationId: post-auth-reset-password
      responses:
        '200':
          description: OK
      tags:
        - Auth Endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                new_password:
                  type: string
                confirm_new_password:
                  type: string
              x-examples:
                Example 1:
                  new_password: '1234'
                  confirm_new_password: '1234'
            examples:
              Example 1:
                value:
                  new_password: '1234'
                  confirm_new_password: '1234'
        description: 'Endpoint untuk reset password, silahkan dimasukkan new password dan confirm new password nya'
  /auth/whoami:
    get:
      summary: Profile Endpoint
      tags:
        - Auth Endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      gender:
                        type: 'null'
                      phone:
                        type: 'null'
                      iat:
                        type: integer
                x-examples:
                  Example 1:
                    status: false
                    message: succes
                    data:
                      id: 4
                      name: dadang
                      email: dada@mail.com
                      role: Buyer
                      gender: null
                      phone: null
                      iat: 1670253655
              examples:
                Example 1:
                  value:
                    status: false
                    message: succes
                    data:
                      id: 4
                      name: dadang
                      email: dada@mail.com
                      role: Buyer
                      gender: null
                      phone: null
                      iat: 1670253655
      operationId: get-auth-whoami
      description: Endpoint ini digunakan untuk cek profile
      parameters:
        - schema:
            type: string
          in: header
          required: true
          name: Authorization
  /list-airport:
    get:
      summary: Airport List Endpoint
      tags:
        - List Airport Endpoint
      responses:
        '200':
          description: Ok.. Data Airport
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        region:
                          type: string
                        code:
                          type:
                            - 'null'
                            - string
                x-examples:
                  Example 1:
                    status: true
                    message: Data dari Port API
                    data:
                      - name: Sultan Aji Muhammad Sulaiman Sepinggan International Airport
                        region: Kalimantan Timur (East Kalimantan)
                        code: BPN
                      - name: Dortheys Hiyo Eluay International Airport
                        region: Papua
                        code: DJJ
              examples:
                Example 1:
                  value:
                    status: true
                    message: Data Airport
                    data:
                      - name: Soeharto Hatta
                        region: Banten
                        code: CGK
      operationId: get-list-airport
      description: Endpoint ini untuk mengambil data list airport yang ada di Indonesia
  /search?:
    get:
      summary: Get All Data Flight Schedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        user_id:
                          type: integer
                        origin_airport:
                          type: string
                        destination_airport:
                          type: string
                        depature_date:
                          type: string
                        return_date:
                          type: string
                        total_passenger:
                          type: integer
                        airlines:
                          type: string
                        depature_time:
                          type: string
                        arrival_time:
                          type: string
                        duration_time:
                          type: string
                        price:
                          type: string
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
                x-examples:
                  Example 1:
                    status: true
                    data:
                      - id: 1
                        user_id: 1
                        origin_airport: KRA
                        destination_airport: SKA
                        depature_date: '2022-12-11'
                        return_date: '2022-12-30'
                        total_passenger: 4
                        airlines: Garuda Indonesia
                        depature_time: '11:00:00'
                        arrival_time: '20:00:00'
                        duration_time: 9 Hours
                        price: '20000'
                        createdAt: '2022-12-13T02:04:10.184Z'
                        updatedAt: '2022-12-13T02:04:10.184Z'
              examples:
                Example 1:
                  value:
                    status: true
                    data:
                      - id: 1
                        user_id: 1
                        origin_airport: KRA
                        destination_airport: SKA
                        depature_date: '2022-12-11'
                        return_date: '2022-12-30'
                        total_passenger: 4
                        airlines: Garuda Indonesia
                        depature_time: '11:00:00'
                        arrival_time: '20:00:00'
                        duration_time: 9 Hours
                        price: '20000'
                        createdAt: '2022-12-13T02:04:10.184Z'
                        updatedAt: '2022-12-13T02:04:10.184Z'
      operationId: get-search?
      description: This endpoint can show all data flight schedule
      parameters:
        - schema:
            type: string
          in: query
          name: oa
          description: Add origin airport
          required: true
        - schema:
            type: string
          in: query
          name: da
          description: Add destination airport
          required: true
        - schema: {}
          in: query
          name: dd
          description: Add departure date
          required: true
        - schema: {}
          in: query
          name: ad
          description: Add arrival date
          required: true
        - schema:
            type: string
          in: query
          description: Add return date
          name: rd
        - schema:
            type: integer
          in: query
          name: tp
          description: Add total passenger
          required: true
      tags:
        - Buyer Endpoint
  /order:
    parameters: []
    post:
      summary: Order Transaction
      operationId: post-order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      phone_number:
                        type: string
                      email:
                        type: string
                x-examples:
                  Example 1:
                    status: false
                    message: Succes
                    data:
                      phone_number: '1230974637235'
                      email: cikskuy@mail.com
              examples:
                Example 1:
                  value:
                    status: false
                    message: Succes
                    data:
                      phone_number: '1230974637235'
                      email: cikskuy@mail.com
      description: Di endpoint ini digunakan untuk menambahkan order data transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderer:
                  type: string
                phone_number:
                  type: string
                email:
                  type: string
              x-examples:
                Example 1:
                  orderer: Cikall
                  phone_number: '1230974637235'
                  email: cikskuy@mail.com
            examples:
              Example 1:
                value:
                  orderer: Cikall
                  phone_number: '1230974637235'
                  email: cikskuy@mail.com
        description: Body yang harus dimasukkan
      tags:
        - Buyer Endpoint
        - Transactions Endpoint
  /passenger:
    parameters: []
    post:
      summary: Order Transaction
      operationId: post-order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      phone_number:
                        type: string
                      email:
                        type: string
                x-examples:
                  Example 1:
                    status: false
                    message: Succes
                    data:
                      phone_number: '1230974637235'
                      email: cikskuy@mail.com
              examples:
                Example 1:
                  value:
                    status: false
                    message: Succes
                    data:
                      phone_number: '1230974637235'
                      email: cikskuy@mail.com
        '':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name_passenger:
                        type: string
                      identity_number:
                        type: string
                      identity_type:
                        type: string
                x-examples:
                  Example 1:
                    status: false
                    message: Succes
                    data:
                      name_passenger: aziz
                      identity_number: '7637002348572198'
                      identity_type: Passport
              examples:
                Example 1:
                  value:
                    status: false
                    message: Succes
                    data:
                      name_passenger: aziz
                      identity_number: '7637002348572198'
                      identity_type: Passport
      description: Di endpoint ini digunakan untuk menambahkan data passenger untuk transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name_passenger:
                  type: string
                identity_number:
                  type: string
                identity_exp_date:
                  type: string
                nationality:
                  type: string
                identity_type:
                  type: string
              x-examples:
                Example 1:
                  name_passenger: aziz
                  identity_number: '7637002348572198'
                  identity_exp_date: 20-10-2022
                  nationality: Turkey
                  identity_type: Passport
            examples:
              Example 1:
                value:
                  name_passenger: aziz
                  identity_number: '7637002348572198'
                  identity_exp_date: 20-10-2022
                  nationality: Turkey
                  identity_type: Passport
        description: Body yang harus dimasukkan
      tags:
        - Buyer Endpoint
        - Transactions Endpoint
  /transaction:
    parameters: []
    post:
      summary: Order Transaction
      operationId: post-order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      phone_number:
                        type: string
                      email:
                        type: string
                x-examples:
                  Example 1:
                    status: false
                    message: Succes
                    data:
                      phone_number: '1230974637235'
                      email: cikskuy@mail.com
              examples:
                Example 1:
                  value:
                    status: false
                    message: Succes
                    data:
                      phone_number: '1230974637235'
                      email: cikskuy@mail.com
        '':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      transaction:
                        type: object
                        properties:
                          id:
                            type: integer
                          PassengerId:
                            type: integer
                          OrderId:
                            type: integer
                          updatedAt:
                            type: string
                          createdAt:
                            type: string
                x-examples:
                  Example 1:
                    status: false
                    message: Succes
                    data:
                      transaction:
                        id: 1
                        PassengerId: 1
                        OrderId: 1
                        updatedAt: '2022-12-14T10:24:19.816Z'
                        createdAt: '2022-12-14T10:24:19.816Z'
              examples:
                Example 1:
                  value:
                    status: false
                    message: Succes
                    data:
                      transaction:
                        id: 1
                        PassengerId: 1
                        OrderId: 1
                        updatedAt: '2022-12-14T10:24:19.816Z'
                        createdAt: '2022-12-14T10:24:19.816Z'
      description: Di endpoint ini digunakan untuk menambahkan data untuk transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                OrderId:
                  type: string
                PassengerId:
                  type: string
              x-examples:
                Example 1:
                  OrderId: '1'
                  PassengerId: '1'
            examples:
              Example 1:
                value:
                  OrderId: '1'
                  PassengerId: '1'
        description: Body yang harus dimasukkan
      tags:
        - Buyer Endpoint
        - Transactions Endpoint
  '/transaction/{transaction_id}':
    parameters:
      - schema:
          type: string
        name: transaction_id
        in: path
        required: true
    get:
      summary: Get data transactions
      operationId: get-transaction---copy
      responses:
        '200':
          description: OK
        '':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      transaction:
                        type: object
                        properties:
                          id:
                            type: integer
                          OrderId:
                            type: integer
                          PassengerId:
                            type: integer
                          passenger:
                            type: object
                            properties:
                              id:
                                type: integer
                              name_passenger:
                                type: string
                              identity_number:
                                type: string
                              nationality:
                                type: string
                              identity_type:
                                type: string
                          order:
                            type: object
                            properties:
                              id:
                                type: integer
                              orderer:
                                type: string
                              phone_number:
                                type: string
                              email:
                                type: string
                x-examples:
                  Example 1:
                    message: Transactions data 1 has been found
                    success: true
                    data:
                      transaction:
                        id: 1
                        OrderId: 1
                        PassengerId: 1
                        passenger:
                          id: 1
                          name_passenger: aziz
                          identity_number: '7637002348572198'
                          nationality: Turkey
                          identity_type: Passport
                        order:
                          id: 1
                          orderer: Cikall
                          phone_number: '1230974637235'
                          email: cikskuy@mail.com
              examples:
                Example 1:
                  value:
                    message: Transactions data 1 has been found
                    success: true
                    data:
                      transaction:
                        id: 1
                        OrderId: 1
                        PassengerId: 1
                        passenger:
                          id: 1
                          name_passenger: aziz
                          identity_number: '7637002348572198'
                          nationality: Turkey
                          identity_type: Passport
                        order:
                          id: 1
                          orderer: Cikall
                          phone_number: '1230974637235'
                          email: cikskuy@mail.com
      parameters:
        - schema:
            type: string
          in: query
          name: '{transaction_id}'
          description: Add transactions Id
      description: Endpoint ini digunakan untuk mengambil data transaction berdasarkan order id dan passenger id
      tags:
        - Buyer Endpoint
        - Transactions Endpoint
  /search:
    parameters: []
    put:
      summary: Edit schedule list endpoint
      operationId: put-search
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      airlines:
                        type: string
                      depature_time:
                        type: string
                      arrival_time:
                        type: string
                      duration_time:
                        type: string
                      price:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    message: success
                    data:
                      airlines: Garuda
                      depature_time: '2022-12-10'
                      arrival_time: '2022-12-10'
                      duration_time: '6'
                      price: '6000000'
              examples:
                Example 1:
                  value:
                    status: true
                    message: success
                    data:
                      airlines: Garuda
                      depature_time: '2022-12-10'
                      arrival_time: '2022-12-10'
                      duration_time: '6'
                      price: '6000000'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: Diendpoint ini admin dapat mengubah jadwal penerbangan pesawat
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: only admin can access this endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                airlines:
                  type: string
                depature_time:
                  type: string
                arrival_time:
                  type: string
                duration_time:
                  type: string
                price:
                  type: string
              x-examples:
                Example 1:
                  airlines: Garuda
                  depature_time: '2022-12-10'
                  arrival_time: '2022-12-10'
                  duration_time: '6'
                  price: '6000000'
            examples:
              Example 1:
                value:
                  airlines: Garuda
                  depature_time: '2022-12-10'
                  arrival_time: '2022-12-10'
                  duration_time: '6'
                  price: '6000000'
        description: 'Hal hal yang bisa di edit, tidak harus semua field diedit'
      tags:
        - Search Endpoint
  '/search/:id':
    parameters: []
    delete:
      summary: Delete Schedule Flight List Endpoint
      operationId: delete-search---copy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Example 1:
                  value:
                    message: Success delete data
      tags:
        - Search Endpoint
      description: Endpoint ini digunakan untuk menghapus Schedule Flight
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: only admin can delete data
  /route:
    parameters: []
    post:
      summary: Add schedule flight list
      operationId: post-search-admin
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      user_id:
                        type: integer
                      origin_airport:
                        type: string
                      destination_airport:
                        type: string
                      depature_date:
                        type: string
                      return_date:
                        type: string
                      total_passenger:
                        type: integer
                      airlines:
                        type: string
                      depature_time:
                        type: string
                      arrival_time:
                        type: string
                      duration_time:
                        type: 'null'
                      price:
                        type: string
                      updatedAt:
                        type: string
                      createdAt:
                        type: string
                x-examples:
                  Example 1:
                    status: false
                    message: Succes
                    data:
                      id: 1
                      user_id: 1
                      origin_airport: Solo
                      destination_airport: Jakarta
                      depature_date: '2022-12-11'
                      return_date: '2022-12-30'
                      total_passenger: 2
                      airlines: Garuda Indonesia
                      depature_time: '10:00:00'
                      arrival_time: '12:00:00'
                      duration_time: null
                      price: '20000'
                      updatedAt: '2022-12-14T09:48:39.883Z'
                      createdAt: '2022-12-14T09:48:39.883Z'
              examples:
                Example 1:
                  value:
                    status: false
                    message: Succes
                    data:
                      id: 1
                      user_id: 1
                      origin_airport: Solo
                      destination_airport: Jakarta
                      depature_date: '2022-12-11'
                      return_date: '2022-12-30'
                      total_passenger: 2
                      airlines: Garuda Indonesia
                      depature_time: '10:00:00'
                      arrival_time: '12:00:00'
                      duration_time: null
                      price: '20000'
                      updatedAt: '2022-12-14T09:48:39.883Z'
                      createdAt: '2022-12-14T09:48:39.883Z'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
        '':
          content:
            application/json:
              schema:
                type: object
                properties: {}
          description: Success
      description: Di endpoint ini admin dapat menambahkan list jadwal penerbangan
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                origin_airport:
                  type: string
                destination_airport:
                  type: string
                depature_date:
                  type: string
                return_date:
                  type: string
                total_passenger:
                  type: string
                depature_time:
                  type: string
                arrival_time:
                  type: string
                price:
                  type: string
              x-examples:
                Example 1:
                  origin_airport: Solo
                  destination_airport: Jakarta
                  depature_date: '2022-12-11'
                  return_date: '2022-12-30'
                  total_passenger: '2'
                  depature_time: '10:00'
                  arrival_time: '12:00'
                  price: '20000'
            examples:
              Example 1:
                value:
                  origin_airport: Solo
                  destination_airport: Jakarta
                  depature_date: '2022-12-11'
                  return_date: '2022-12-30'
                  total_passenger: '2'
                  depature_time: '10:00'
                  arrival_time: '12:00'
                  price: '20000'
        description: 'Kamu dapat memasukkan data berikut '
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: authorization for admin needed
      tags:
        - Admin Endpoint
components:
  securitySchemes: {}
